#!/usr/bin/env bash
# tinty hook: apply $XDG_STATE_HOME/theme/palette.json to tmux.
#
# - Writes ~/.config/tmux/theme.conf: the @thm_* colours that tmux.conf's status
#   line formats refer to, plus the styles that take plain colours.
# - Sources it into the running tmux server, if any.
#
# Must run after ~/.config/quickshell/tinty-hook.sh, which writes palette.json
# (tinty runs hooks in the order listed in its config.toml).
set -euo pipefail

palette=${XDG_STATE_HOME:-$HOME/.local/state}/theme/palette.json
theme=${XDG_CONFIG_HOME:-$HOME/.config}/tmux/theme.conf

# "#rrggbb" for a palette slot
hex() { jq -r --arg key "$1" '.palette[$key]' "$palette"; }

tmp=$(mktemp "$theme.XXXXXX")
cat >"$tmp" <<EOF
# Generated by ~/.config/tmux/tinty-hook.sh from $(jq -r .name "$palette"); edits are overwritten.
set -g @thm_bg "$(hex base00)"
set -g @thm_surface "$(hex base01)"
set -g @thm_muted "$(hex base04)"
set -g @thm_fg "$(hex base05)"
set -g @thm_accent "$(hex base0D)"
set -g @thm_application "$(hex base0E)"
set -g @thm_session "$(hex base0B)"
set -g @thm_prefix "$(hex base08)"
set -g @thm_uptime "$(hex base0C)"

set -g status-style "bg=$(hex base00),fg=$(hex base05)"
set -g pane-border-style "fg=$(hex base02)"
set -g pane-active-border-style "fg=$(hex base0D)"
set -g message-style "bg=$(hex base01),fg=$(hex base05)"
set -g message-command-style "bg=$(hex base01),fg=$(hex base05)"
set -g mode-style "bg=$(hex base02),fg=$(hex base05)"
set -g copy-mode-match-style "bg=$(hex base03),fg=$(hex base05)"
set -g copy-mode-current-match-style "bg=$(hex base0A),fg=$(hex base00)"
set -g menu-style "bg=$(hex base01),fg=$(hex base05)"
set -g menu-selected-style "bg=$(hex base02),fg=$(hex base05)"
set -g menu-border-style "fg=$(hex base03)"
set -g popup-border-style "fg=$(hex base03)"
set -g display-panes-colour "$(hex base03)"
set -g display-panes-active-colour "$(hex base0D)"
set -g clock-mode-colour "$(hex base0D)"
EOF
chmod 644 "$tmp"
mv "$tmp" "$theme"

# No-op when no tmux server is running.
tmux source-file "$theme" 2>/dev/null || true
