#!/usr/bin/env bash
# tinty hook: apply $XDG_STATE_HOME/theme/palette.json to btop.
#
# - Writes ~/.config/btop/themes/tinty.theme, which btop.conf selects with
#   `color_theme = "tinty"`.
# - Signals running btop instances to reload their config (SIGUSR2).
#
# Must run after ~/.config/quickshell/tinty-hook.sh, which writes palette.json
# (tinty runs hooks in the order listed in its config.toml).
set -euo pipefail

palette=${XDG_STATE_HOME:-$HOME/.local/state}/theme/palette.json
themes=${XDG_CONFIG_HOME:-$HOME/.config}/btop/themes

# "#rrggbb" for a palette slot. "Hot" ends of gradients use base12 (bright red):
# some schemes' base08 isn't red, and palette.json fills base12 from base08 for
# base16 schemes.
hex() { jq -r --arg key "$1" '.palette[$key]' "$palette"; }

mkdir -p "$themes"
tmp=$(mktemp "$themes/.tinty.XXXXXX")
cat >"$tmp" <<THEME
# Generated by ~/.config/btop/tinty-hook.sh from $(jq -r .name "$palette"); edits are overwritten.
theme[main_bg]="$(hex base00)"
theme[main_fg]="$(hex base05)"
theme[title]="$(hex base05)"
theme[hi_fg]="$(hex base0D)"
theme[selected_bg]="$(hex base02)"
theme[selected_fg]="$(hex base05)"
theme[inactive_fg]="$(hex base03)"
theme[graph_text]="$(hex base04)"
theme[meter_bg]="$(hex base02)"
theme[proc_misc]="$(hex base0D)"
theme[div_line]="$(hex base02)"

theme[cpu_box]="$(hex base0B)"
theme[mem_box]="$(hex base0A)"
theme[net_box]="$(hex base0E)"
theme[proc_box]="$(hex base0D)"

theme[temp_start]="$(hex base0B)"
theme[temp_mid]="$(hex base0A)"
theme[temp_end]="$(hex base12)"
theme[cpu_start]="$(hex base0B)"
theme[cpu_mid]="$(hex base0A)"
theme[cpu_end]="$(hex base12)"
theme[free_start]="$(hex base0B)"
theme[free_mid]="$(hex base0B)"
theme[free_end]="$(hex base0C)"
theme[cached_start]="$(hex base0D)"
theme[cached_mid]="$(hex base0D)"
theme[cached_end]="$(hex base0C)"
theme[available_start]="$(hex base0A)"
theme[available_mid]="$(hex base0A)"
theme[available_end]="$(hex base0B)"
theme[used_start]="$(hex base0B)"
theme[used_mid]="$(hex base0A)"
theme[used_end]="$(hex base12)"
theme[download_start]="$(hex base0C)"
theme[download_mid]="$(hex base0D)"
theme[download_end]="$(hex base0E)"
theme[upload_start]="$(hex base0C)"
theme[upload_mid]="$(hex base0D)"
theme[upload_end]="$(hex base0E)"
theme[process_start]="$(hex base0B)"
theme[process_mid]="$(hex base0A)"
theme[process_end]="$(hex base12)"
THEME
chmod 644 "$tmp"
mv "$tmp" "$themes/tinty.theme"

# btop reloads its config (and so the theme) on SIGUSR2; no-op when none is running.
pkill -USR2 -x btop || true
