#!/usr/bin/env bash
# tinty hook: apply $XDG_STATE_HOME/theme/palette.json to lazygit.
#
# - Writes ~/.config/lazygit/tinty.yml, a config file with the theme only. lazygit
#   merges it over config.yml because ~/.zshrc lists both in LG_CONFIG_FILE.
# - Running lazygit instances pick the change up when their terminal regains focus
#   (lazygit then reloads config files that changed).
#
# Inside Neovim, snacks.nvim appends its own theme (from the tinty colorscheme).
#
# Must run after ~/.config/quickshell/tinty-hook.sh, which writes palette.json
# (tinty runs hooks in the order listed in its config.toml).
set -euo pipefail

palette=${XDG_STATE_HOME:-$HOME/.local/state}/theme/palette.json
theme=${XDG_CONFIG_HOME:-$HOME/.config}/lazygit/tinty.yml

# "#rrggbb" for a palette slot. Unstaged changes use base12 (bright red): some
# schemes' base08 isn't red, and palette.json fills base12 from base08 for base16
# schemes.
hex() { jq -r --arg key "$1" '.palette[$key]' "$palette"; }

tmp=$(mktemp "$theme.XXXXXX")
cat >"$tmp" <<YAML
# Generated by ~/.config/lazygit/tinty-hook.sh from $(jq -r .name "$palette"); edits are overwritten.
gui:
  theme:
    activeBorderColor: ["$(hex base0D)", bold]
    inactiveBorderColor: ["$(hex base03)"]
    searchingActiveBorderColor: ["$(hex base0A)", bold]
    optionsTextColor: ["$(hex base0D)"]
    selectedLineBgColor: ["$(hex base02)"]
    inactiveViewSelectedLineBgColor: ["$(hex base01)"]
    cherryPickedCommitFgColor: ["$(hex base00)"]
    cherryPickedCommitBgColor: ["$(hex base0C)"]
    markedBaseCommitFgColor: ["$(hex base00)"]
    markedBaseCommitBgColor: ["$(hex base0A)"]
    unstagedChangesColor: ["$(hex base12)"]
    defaultFgColor: ["$(hex base05)"]
YAML
chmod 644 "$tmp"
mv "$tmp" "$theme"
