#!/usr/bin/env bash
# tinty hook: apply $XDG_STATE_HOME/theme/palette.json to Ghostty.
#
# - Writes ~/.config/ghostty/themes/tinty, which the Ghostty config selects with
#   `theme = tinty`.
# - Signals running Ghostty instances to reload their config (SIGUSR2).
#
# Must run after ~/.config/quickshell/tinty-hook.sh, which writes palette.json
# (tinty runs hooks in the order listed in its config.toml).
set -euo pipefail

palette=${XDG_STATE_HOME:-$HOME/.local/state}/theme/palette.json
themes=${XDG_CONFIG_HOME:-$HOME/.config}/ghostty/themes

# "#rrggbb" for a palette slot
hex() { jq -r --arg key "$1" '.palette[$key]' "$palette"; }

# ANSI colours as in tinted-terminal's Ghostty template: normal colours from base16
# slots, bright ones from base24's base12-base17 (palette.json fills these in for
# base16 schemes).
mkdir -p "$themes"
tmp=$(mktemp "$themes/.tinty.XXXXXX")
cat >"$tmp" <<EOF
# Generated by ~/.config/ghostty/tinty-hook.sh from $(jq -r .name "$palette"); edits are overwritten.
background = $(hex base00)
foreground = $(hex base05)
cursor-color = $(hex base05)
cursor-text = $(hex base00)
selection-background = $(hex base02)
selection-foreground = $(hex base05)
split-divider-color = $(hex base02)

palette = 0=$(hex base00)
palette = 1=$(hex base08)
palette = 2=$(hex base0B)
palette = 3=$(hex base0A)
palette = 4=$(hex base0D)
palette = 5=$(hex base0E)
palette = 6=$(hex base0C)
palette = 7=$(hex base05)
palette = 8=$(hex base03)
palette = 9=$(hex base12)
palette = 10=$(hex base14)
palette = 11=$(hex base13)
palette = 12=$(hex base16)
palette = 13=$(hex base17)
palette = 14=$(hex base15)
palette = 15=$(hex base07)
EOF
chmod 644 "$tmp"
mv "$tmp" "$themes/tinty"

# Ghostty reloads its config on SIGUSR2; no-op when none is running.
pkill -USR2 -x ghostty || true
