#!/usr/bin/env bash
# tinty hook: apply $XDG_STATE_HOME/theme/palette.json to the Hypr ecosystem.
#
# - Writes ~/.config/hypr/hyprtoolkit.conf (hyprlauncher and other hyprtoolkit apps
#   watch it and recolour live).
# - Reloads Hyprland so hyprland.lua re-reads the palette.
#
# Must run after ~/.config/quickshell/tinty-hook.sh, which writes palette.json
# (tinty runs hooks in the order listed in its config.toml).
set -euo pipefail

palette=${XDG_STATE_HOME:-$HOME/.local/state}/theme/palette.json
toolkit=${XDG_CONFIG_HOME:-$HOME/.config}/hypr/hyprtoolkit.conf

# "rgb(rrggbb)" for a palette slot
rgb() { jq -r --arg key "$1" '.palette[$key] | "rgb(" + ltrimstr("#") + ")"' "$palette"; }

# Written in place rather than replaced: hyprtoolkit watches the file itself.
cat >"$toolkit" <<EOF
# Generated by ~/.config/hypr/tinty-hook.sh from $(jq -r .name "$palette"); edits are overwritten.
background = $(rgb base00)
base = $(rgb base01)
alternate_base = $(rgb base02)
text = $(rgb base05)
bright_text = $(rgb base06)
accent = $(rgb base0D)
accent_secondary = $(rgb base0C)
EOF

# Nothing more to do outside a Hyprland session (e.g. tinty run over ssh).
[[ -n ${HYPRLAND_INSTANCE_SIGNATURE:-} ]] || exit 0
hyprctl reload >/dev/null
