#!/usr/bin/env bash
# tinty hook: apply $XDG_STATE_HOME/theme/palette.json to the Hypr ecosystem.
#
# - Writes ~/.config/hypr/hyprtoolkit.conf (hyprlauncher and other hyprtoolkit apps
#   watch it and recolour live).
# - Reloads Hyprland so hyprland.lua re-reads the palette.
# - Frames the scheme's wallpaper and sets it in hyprpaper.
#
# Must run after ~/.config/quickshell/tinty-hook.sh, which writes palette.json
# (tinty runs hooks in the order listed in its config.toml).
set -euo pipefail

palette=${XDG_STATE_HOME:-$HOME/.local/state}/theme/palette.json
toolkit=${XDG_CONFIG_HOME:-$HOME/.config}/hypr/hyprtoolkit.conf

# "rgb(rrggbb)" for a palette slot
rgb() { jq -r --arg key "$1" '.palette[$key] | "rgb(" + ltrimstr("#") + ")"' "$palette"; }

# Written in place rather than replaced: hyprtoolkit watches the file itself.
cat >"$toolkit" <<EOF
# Generated by ~/.config/hypr/tinty-hook.sh from $(jq -r .name "$palette"); edits are overwritten.
background = $(rgb base00)
base = $(rgb base01)
alternate_base = $(rgb base02)
text = $(rgb base05)
bright_text = $(rgb base06)
accent = $(rgb base0D)
accent_secondary = $(rgb base0C)
EOF

# hyprtoolkit <0.6 spins at 100% CPU forever once its watched config changes (fixed
# upstream in e51fde5), so restart its apps instead of relying on the live reload.
# hyprlauncher is started on demand by the menu bind; hyprpaper is restarted below.
pkill -x hyprlauncher || true

# Fresh hyprpaper, detached from tinty; reads the wallpaper.png link via hyprpaper.conf.
restart_hyprpaper() {
    pkill -x hyprpaper || true
    for _ in {1..40}; do pgrep -x hyprpaper >/dev/null || break; sleep 0.05; done
    setsid -f hyprpaper >/dev/null 2>&1
}

# Nothing more to do outside a Hyprland session (e.g. tinty run over ssh).
[[ -n ${HYPRLAND_INSTANCE_SIGNATURE:-} ]] || exit 0
hyprctl reload >/dev/null

# Wallpaper: the scheme's image from ~/pictures/wallpapers (see the README there), framed
# in base00 by frame-wallpaper, linked as $state/wallpaper.png for hyprpaper.conf and
# shown by restarting hyprpaper. Each framed image gets its own name, so hyprpaper never
# shows a cached one.
wallpapers=$HOME/pictures/wallpapers
state=$(dirname "$palette")

# Most specific name first: base16-gruvbox-dark-hard tries gruvbox-dark-hard,
# gruvbox-dark, gruvbox, then default-<variant>.
find_wallpaper() {
    local name file
    name=$(jq -r '.theme | sub("^base(16|24)-"; "")' "$palette")
    while :; do
        for file in "$wallpapers/$name".{png,jpg,jpeg,webp,jxl}; do
            [[ -f $file ]] && { echo "$file"; return; }
        done
        [[ $name == *-* ]] || break
        name=${name%-*}
    done
    for file in "$wallpapers/default-$(jq -r '.variant // "dark"' "$palette")".{png,jpg,jpeg,webp,jxl}; do
        [[ -f $file ]] && { echo "$file"; return; }
    done
    return 1
}

image=$(find_wallpaper) || {
    echo "tinty-hook: no wallpaper for this scheme in $wallpapers" >&2
    restart_hyprpaper
    exit 0
}
framed=$state/wallpaper-$(date +%s%N).png
frame-wallpaper "$image" "$framed" >/dev/null
ln -sfn "$(basename "$framed")" "$state/wallpaper.png"
# Same image for the SDDM login screen; the installed copy is writable once
# ~/.local/share/sddm-themes/hypr-glass/install.sh has been run.
cp "$framed" "$HOME/.local/share/sddm-themes/hypr-glass/background.png"
sddm_bg=/usr/share/sddm/themes/hypr-glass/background.png
[[ -w $sddm_bg ]] && cp "$framed" "$sddm_bg"
restart_hyprpaper
find "$state" -maxdepth 1 -name 'wallpaper-*.png' ! -path "$framed" -delete
