#!/usr/bin/env bash
# tinty hook: apply $XDG_STATE_HOME/theme/palette.json to dunst.
#
# - Writes ~/.config/dunst/dunstrc.d/50-tinty.conf, a drop-in with the colours only
#   (dunst reads it next to ~/.config/dunst/dunstrc).
# - Reloads the running dunst, if any.
#
# Must run after ~/.config/quickshell/tinty-hook.sh, which writes palette.json
# (tinty runs hooks in the order listed in its config.toml).
set -euo pipefail

palette=${XDG_STATE_HOME:-$HOME/.local/state}/theme/palette.json
dropin=${XDG_CONFIG_HOME:-$HOME/.config}/dunst/dunstrc.d/50-tinty.conf

# "#rrggbb" for a palette slot. Critical uses base12 (bright red): some schemes'
# base08 isn't red (Tokyo Night Dark's is #c0caf5), and palette.json fills base12
# from base08 for base16 schemes.
hex() { jq -r --arg key "$1" '.palette[$key]' "$palette"; }

mkdir -p "$(dirname "$dropin")"
tmp=$(mktemp "$dropin.XXXXXX")
cat >"$tmp" <<CONF
# Generated by ~/.config/dunst/tinty-hook.sh from $(jq -r .name "$palette"); edits are overwritten.
[global]
    separator_color = frame
    highlight = "$(hex base0D)"

[urgency_low]
    background = "$(hex base01)"
    foreground = "$(hex base04)"
    frame_color = "$(hex base03)"

[urgency_normal]
    background = "$(hex base01)"
    foreground = "$(hex base05)"
    frame_color = "$(hex base0D)"

[urgency_critical]
    background = "$(hex base01)"
    foreground = "$(hex base05)"
    frame_color = "$(hex base12)"
    highlight = "$(hex base12)"
CONF
chmod 644 "$tmp"
mv "$tmp" "$dropin"

# No-op when dunst isn't running.
dunstctl reload 2>/dev/null || true
