#!/usr/bin/env bash
# tinty hook: apply $XDG_STATE_HOME/theme/palette.json to walker.
#
# - Writes ~/.config/walker/themes/tinty/colors.css, which the theme's style.css imports.
# - Restarts the walker service, if running, so it picks up the new colours.
#
# Must run after ~/.config/quickshell/tinty-hook.sh, which writes palette.json
# (tinty runs hooks in the order listed in its config.toml).
set -euo pipefail

palette=${XDG_STATE_HOME:-$HOME/.local/state}/theme/palette.json
colors=${XDG_CONFIG_HOME:-$HOME/.config}/walker/themes/tinty/colors.css

# "#rrggbb" for a palette slot. Errors use base12 (bright red): some schemes' base08
# isn't red, and palette.json fills base12 from base08 for base16 schemes.
hex() { jq -r --arg key "$1" '.palette[$key]' "$palette"; }

mkdir -p "$(dirname "$colors")"
tmp=$(mktemp "$colors.XXXXXX")
cat >"$tmp" <<CSS
/* Generated by ~/.config/walker/tinty-hook.sh from $(jq -r .name "$palette"); edits are overwritten. */
@define-color window_bg_color $(hex base00);
@define-color accent_bg_color $(hex base0D);
@define-color theme_fg_color $(hex base05);
@define-color error_bg_color $(hex base12);
@define-color error_fg_color $(hex base00);
CSS
chmod 644 "$tmp"
mv "$tmp" "$colors"

# The service keeps its CSS loaded; restart it detached from tinty.
if pkill -x walker; then
    for _ in {1..40}; do pgrep -x walker >/dev/null || break; sleep 0.05; done
    [[ -n ${WAYLAND_DISPLAY:-} ]] && setsid -f walker --gapplication-service >/dev/null 2>&1
fi
exit 0
