#!/usr/bin/env bash
# tinty hook: apply $XDG_STATE_HOME/theme/palette.json to GTK apps.
#
# - Writes ~/.config/gtk-4.0/tinty.css (libadwaita CSS variables) and
#   ~/.config/gtk-3.0/tinty.css (@define-color names, which only the adw-gtk3 theme
#   reads; stock GTK3 Adwaita ignores them). Each directory's gtk.css imports its
#   tinty.css, so gtk.css stays hand-editable.
# - Sets the GNOME color-scheme from the scheme's variant (libadwaita apps follow it
#   live), and the adw-gtk3 theme variant when adw-gtk3 is installed.
#
# GTK only reads gtk.css at startup, so colours reach apps started after this runs.
#
# Must run after ~/.config/quickshell/tinty-hook.sh, which writes palette.json
# (tinty runs hooks in the order listed in its config.toml).
set -euo pipefail

palette=${XDG_STATE_HOME:-$HOME/.local/state}/theme/palette.json
config=${XDG_CONFIG_HOME:-$HOME/.config}

# "#rrggbb" for a palette slot
hex() { jq -r --arg key "$1" '.palette[$key]' "$palette"; }

# libadwaita colour name -> palette slot. Red roles use base12 (bright red): some
# schemes' base08 isn't red, and palette.json fills base12 from base08 for base16
# schemes.
colors=(
    window-bg base00 window-fg base05
    view-bg base00 view-fg base05
    headerbar-bg base01 headerbar-fg base05 headerbar-backdrop base00 headerbar-border base05
    sidebar-bg base01 sidebar-fg base05 sidebar-backdrop base00
    secondary-sidebar-bg base01 secondary-sidebar-fg base05 secondary-sidebar-backdrop base00
    card-bg base01 card-fg base05
    dialog-bg base01 dialog-fg base05
    popover-bg base01 popover-fg base05
    overview-bg base00 overview-fg base05
    thumbnail-bg base01 thumbnail-fg base05
    accent base0D accent-bg base0D accent-fg base00
    destructive base12 destructive-bg base12 destructive-fg base00
    error base12 error-bg base12 error-fg base00
    success base0B success-bg base0B success-fg base00
    warning base0A warning-bg base0A warning-fg base00
)

header="/* Generated by ~/.config/gtk-3.0/tinty-hook.sh from $(jq -r .name "$palette"); edits are overwritten. */"

# write <file>: stdin to <file>, atomically
write() {
    local tmp
    tmp=$(mktemp "$1.XXXXXX")
    cat >"$tmp"
    chmod 644 "$tmp"
    mv "$tmp" "$1"
}

{
    echo "$header"
    echo ":root {"
    for ((i = 0; i < ${#colors[@]}; i += 2)); do
        echo "  --${colors[i]}-color: $(hex "${colors[i + 1]}");"
    done
    echo "}"
} | write "$config/gtk-4.0/tinty.css"

{
    echo "$header"
    for ((i = 0; i < ${#colors[@]}; i += 2)); do
        echo "@define-color ${colors[i]//-/_}_color $(hex "${colors[i + 1]}");"
    done
} | write "$config/gtk-3.0/tinty.css"

if [[ $(jq -r .variant "$palette") == light ]]; then
    scheme=prefer-light theme=adw-gtk3
else
    scheme=prefer-dark theme=adw-gtk3-dark
fi
gsettings set org.gnome.desktop.interface color-scheme "$scheme"
if [[ -d /usr/share/themes/$theme ]]; then
    gsettings set org.gnome.desktop.interface gtk-theme "$theme"
fi
